name: SpeedRankUP
author: Needev
main: br.com.speedmc.SpeedRankUP
version: 1.0

commands:
  broadcast:
    aliases: [bc, aviso, avisar]
  bcgold:
  executarvipextra:
  newplayer:
  feed:
    aliases: [comer, comida]