name: SpeedPvP
author: Needev
main: br.com.speedmc.SpeedPvP
version: 1.0

commands:
  broadcast:
    aliases: [bc, aviso, avisar]
  bcgold:
  executarvipextra:
  newplayer:
  feed:
    aliases: [comer, comida]
  setchain:
  chain:
  comprarpasse: